layout_spectrum: 1
typography_spectrum: 0.5276596
color:
  lightness: 1
  brandStrength: 0.0179566
  saturation: 0.4851064
  rhythmicContrast: 1
  brandColors:
    - '#FFFFFF'
    - '#020103'
    - '#434143'
    - '#817F81'
name: 'Brogan Production Studios '
